services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      REMBG_HOME: /opt/rembg
    command: ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - backend

networks:
  backend:
    external: true
    name: backend
